app = "unconditional-server"
kill_signal = "SIGINT"
kill_timeout = 1
processes = []

[build]
  secrets = ["UNCONDITIONAL_API_SOURCE_CLIENT_KEY"] 

[build.args]
  UNCONDITIONAL_API_ADDRESS="0.0.0.0"
  UNCONDITIONAL_API_PORT="8080"
  UNCONDITIONAL_API_ALLOWED_ORIGINS="https://unconditional.day,https://www.unconditional.day"
  UNCONDITIONAL_API_SOURCE_REPO="source"
  UNCONDITIONAL_API_LOG_ENV="prod"

[env]
  UNCONDITIONAL_API_ADDRESS="0.0.0.0"
  UNCONDITIONAL_API_PORT="8080"
  UNCONDITIONAL_API_ALLOWED_ORIGINS="https://unconditional.day,https://www.unconditional.day"
  UNCONDITIONAL_API_SOURCE_REPO="source"
  UNCONDITIONAL_API_LOG_ENV="prod"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  processes = ["app"]
  protocol = "tcp"
  internal_port = 8080
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    handlers = ["tls"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "30s"
    interval = "15s"
    restart_limit = 2
    timeout = "10s"
  