app = "unconditional-server"
kill_signal = "SIGINT"
kill_timeout = 20
processes = []

[build.args]
  UNCONDITIONAL_ADDRESS="0.0.0.0"
  UNCONDITIONAL_PORT="8080"

[env]
  UNCONDITIONAL_ADDRESS="0.0.0.0"
  UNCONDITIONAL_PORT="8080"
  
[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  processes = ["app"]
  protocol = "tcp"
  internal_port = 8080
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    handlers = ["tls"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "30s"
    interval = "15s"
    restart_limit = 2
    timeout = "10s"
