-- +goose Up
CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE EXTENSION IF NOT EXISTS fuzzystrmatch;

-- +goose Down
DROP EXTENSION IF NOT EXISTS vector;
DROP EXTENSION IF NOT EXISTS pg_trgm;
DROP EXTENSION IF NOT EXISTS fuzzystrmatch;
