name: Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
          cache: true
      - name: Prepare tools
        run: make install-tools
      - name: Get dependencies
        run: go get -v -t -d ./...
      - name: Install dependencies
        run: go mod download
      - name: Unit test
        run: make test-unit
      - name: Integration test
        run: make test-integration
      - name: Build
        run: make build
