name: Deploy
on:
  push:
    branches:
      - main

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
          cache: true
      - name: Prepare tools
        run: make prepare-ci
      - name: Get dependencies
        run: go get -v -t -d ./...
      - name: Install dependencies
        run: go mod download
      - name: Unit test
        run: make test-unit
      - name: Integration test
        run: make test-integration
      - name: Build
        run: make build
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy
