name: Scheduled Fly Deploy
on:
  schedule:
    - cron: "30 * * * *"

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
        with: 
          version: 1.3
      - run: flyctl deploy --remote-only
