name: Release
on:
  release:
    types: [published]

env:
  UNCONDITIONAL_API_SOURCE_CLIENT_KEY: ${{ secrets.UNCONDITIONAL_API_SOURCE_CLIENT_KEY }}
  UNCONDITIONAL_API_FEED_REPO_HOST: ${{ secrets.UNCONDITIONAL_API_FEED_REPO_HOST }}
  UNCONDITIONAL_API_FEED_REPO_KEY: ${{ secrets.UNCONDITIONAL_API_FEED_REPO_KEY }}
  UNCONDITIONAL_API_BUILD_COMMIT_VERSION: ${{ github.sha }}
  UNCONDITIONAL_API_BUILD_RELEASE_VERSION: ${{ github.event.release.tag_name }}
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  deploy-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
          cache: true
      - name: Prepare tools
        run: make install-tools
      - name: Get dependencies
        run: go get -v -t -d ./...
      - name: Install dependencies
        run: go mod download
      - name: Unit test
        run: make test-unit
      - name: Integration test
        run: make test-integration
      - name: Deploy
        run: chmod +x scripts/deploy.sh && sh scripts/deploy.sh
